### ISSUE TITLE
The image of the arrow does not turn

### ISSUE THREAD

**Issue by Kaijiro** [graphstream/gs-core#123]
When defining a image in the CSS, the image does not turn.

```CSS
edge.white_link{
	arrow-shape : image;
	arrow-image : url('src/com/uqode/monitoring/ressources/white_arrow.png');
}
```

The goal is to display my two edges like this : ---><---
But actually, the CSS makes my edges look like this : --<<---

Do I need to create a other image that is the symetric of the first one or is it an issue ?
