### ISSUE TITLE
How to display arrows on my graph ?

### ISSUE THREAD

**Issue by NicolasSys** [graphstream/gs-core#22]
Hi,

I have a problem while trying to display the whole arrow on my graph. Indeed, the head of the arrow is hidden behind the nodes on which I applied a particular css style :

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/818/arrowheadhidden.png/'><img src='http://img818.imageshack.us/img818/5641/arrowheadhidden.png' border='0'/></a>

Here is the css style of the nodes : 

``` css

node.noeud {
 size-mode: fit;  
 shape: rounded-box;
 fill-color: white; 
 stroke-mode: plain; 
 padding: 4px, 4px; 
 icon-mode: at-left; 
 icon: url('draw/noeud.png'); 
}

```

and the arrow :

``` css

edge.nodeToNode {
 arrow-shape: arrow; 
 arrow-size: 20px, 4px; 
}
```

I would like that my arrow's head points directly onto my nodes and not to continue behind them. 

Is there a css option or something to do that because I've been working on this for a while without finding a solution in the examples or in the tutorials ... ?

I have tried to use the z-index property but it's not what I want either :

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/38/highzindex.png/'><img src='http://img38.imageshack.us/img38/3381/highzindex.png' border='0'/></a>

Thanks,

Nicolas
