### ISSUE TITLE
 overlapping of labels of directed edges pointing to same direction between the same two nodes

### ISSUE THREAD

**Issue by kenchiu21** [graphstream/gs-core#314]
[https://github.com/graphstream/gs-core/issues/103](url)
I have three edges from from node s1 pointing to node s2.
Despite issue 103, I found that text-offset cannot solve the issue.

![image](https://user-images.githubusercontent.com/40093662/54507076-910e9300-497a-11e9-809a-0ccc29929692.png)

```
graph {  
	text-style:normal; 
	text-mode:normal;  
}    

node {
	size: 10px; 
	shape: circle ; 
	stroke-mode: plain; 
	text-mode:normal;
	text-alignment:at-left; 
	text-background-mode:none; 
 } 
  
 edge {
	text-mode:normal; 
	text-alignment:along; 
	text-background-mode:none; 
	text-offset: -10,-10;
 };
```

**Comment by hichbra** [comment]
Use some classes to custom your edges, like : 
```java
graph.getEdge("e1").setAttribute("ui.class", "e1");
graph.getEdge("e2").setAttribute("ui.class", "e2");
graph.getEdge("e3").setAttribute("ui.class", "e3");
```
```css
edge.e1 {fill-color: red; text-offset: -10,-10; }
edge.e2 {fill-color: blue; text-offset: 0,0; }
edge.e3 {fill-color: green; text-offset: 10,10; }
```
![test](https://user-images.githubusercontent.com/10866042/54527657-d6cb5b80-497a-11e9-8656-27d84992df10.png)

Please do not forget to read [our documentation ](http://graphstream-project.org/doc/Advanced-Concepts/GraphStream-CSS-Reference/)which explains many of the issues you could encounter. A large part is still valid even for version 2.0.
Good luck
